export const rashanList = [
    "Acrylic paint",
    "Aluminum foil",
    "Allergy medication",
    "Apples",
    "Avocado",
    "Baking powder",
    "Baking soda",
    "Bananas",
    "Batteries",
    "Beads",
    "Beef broth",
    "Beverages",
    "Binder clips",
    "Bobbins",
    "Body lotion",
    "Bread",
    "Broccoli",
    "Broom",
    "Brown sugar",
    "Bucket",
    "Butter",
    "Cake mix",
    "Calculator",
    "Calendar",
    "Calligraphy paper",
    "Candles",
    "Candy",
    "Canned beans",
    "Canned goods",
    "Canned soup",
    "Canned tomatoes",
    "Canned tuna",
    "Canvas",
    "Canvas board",
    "Canvas paper",
    "Canvas stretchers",
    "Carrots",
    "Cardstock",
    "Cauliflower",
    "Cereals",
    "Cheese",
    "Chicken broth",
    "Chocolates",
    "Cleaning supplies",
    "Cocoa powder",
    "Coffee powder",
    "Condensed milk",
    "Cookies",
    "Cornstarch",
    "Correction fluid",
    "Cosmetics",
    "Craft foam",
    "Craft glue",
    "Craft sticks",
    "Crayons",
    "Cross-stitch fabric",
    "Cucumbers",
    "Dairy products",
    "Diapers",
    "Dish soap",
    "Disinfectant spray",
    "Dried fruit",
    "Drawing paper",
    "Drawing pencils",
    "Dry fruits",
    "Eggs",
    "Elastic",
    "Embroidery floss",
    "Embroidery hoop",
    "Embroidery needles",
    "Embroidery scissors",
    "Energy drinks",
    "Envelopes",
    "Erasers",
    "Evaporated milk",
    "Fabric glue",
    "Fabric markers",
    "Fabric paint",
    "Fabric scissors",
    "Fabric softener",
    "Flour",
    "Fresh fruit",
    "Fresh vegetables",
    "Frosting",
    "Garlic",
    "Gelatin",
    "Ginger",
    "Granola",
    "Grapes",
    "Herbs",
    "Herbs (basil, parsley, cilantro)",
    "Honey",
    "Hot sauce",
    "Jam",
    "Juice",
    "Ketchup",
    "Lemons",
    "Lettuce",
    "Limes",
    "Margarine",
    "Mayonnaise",
    "Melons",
    "Milk",
    "Mineral water",
    "Mushrooms",
    "Mustard",
    "Nuts",
    "Oatmeal",
    "Olive oil",
    "Onions",
    "Orange",
    "Pasta",
    "Peanut butter",
    "Pepper",
    "Pineapple",
    "Potatoes",
    "Powdered sugar",
    "Pudding mix",
    "Rice",
    "Salt",
    "Seeds",
    "Soy sauce",
    "Sparkling water",
    "Spices",
    "Spinach",
    "Sugar",
    "Tea",
    "Tomato sauce",
    "Tomatoes",
    "Vegetable broth",
    "Vegetable oil",
    "Vinegar",
    "Yogurt",
    "Zucchini"
  ];
  