export const ProductList = [
    "Cake mix",
    "Apples",
    "Brown sugar",
    "Baking soda",
    "Bread",
    "Broom",
    "Bobbins",
    "Broccoli",
    "Binder clips",
    "Beef broth",
    "Canned soup",
    "Bucket",
    "Calendar",
    "Beverages",
    "Bananas",
    "Canned goods",
    "Acrylic paint",
    "Aluminum foil",
    "Body lotion",
    "Baking powder",
    "Batteries",
    "Calculator",
    "Beads",
    "Canned beans",
    "Calligraphy paper",
    "Candy"
  ]
  